name: deploy-app

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'client/src/**'
      - 'client/package.json'
      - 'backend/src/**'
      - 'backend/package.json'
      - '.github/workflows/**'

defaults:
  run:
    working-directory: '.'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd client && npm install
